services:
  bot:
    image: ${GHCR_IMAGE_NAME:-ghcr.io/mageri9/m9_imagebot}:latest
    container_name: m9_imagebot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - m9_imagebot_net
      - nexus_shared


volumes:
  m9_imagebot_redis_data:

networks:
  m9_imagebot_net:
    driver: bridge
  nexus_shared:
    external: true